spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    properties:
      hibernate :
        show_sql : true
project:
  name: Pepperfry Product Service
  version: 1.0.0-SNAPSHOT   
